### ISSUE TITLE
Qalculate: Hash does not match for v3.2.0/qalculate-3.2.0-x64.msi

### ISSUE THREAD

**Issue by cmorty** [C4illin/Choco-Packages#1]

**Comment by C4illin** [comment]
I'm sorry this took so long to fix and that I then took so long to respond. The problem is that the installer sometimes changed without a change in the version number, which was a bit troublesome to automate. So this is a manual fix for now.

**Comment by C4illin** [comment]
I will close this issue since the problem hasn't occurred in a long time.
